# Generated by Django 4.2.27 on 2026-02-26 16:36

from django.conf import settings
from django.db import migrations, models


from NEMO.apps.nemo_ce.migration_utils import NEMOMigration


class Migration(NEMOMigration):

    dependencies = [
        ("NEMO", "0142_alter_tool__adjustment_request_reviewers_and_more"),
        ("nemo_ce", "0027_ce_qualification_level_during_closures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="_allow_user_shadowing_verification_request",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to request qualification on this tool through shadowing verification.",
                verbose_name="allow user shadowing verification request",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_grant_access_for_qualification_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Granting physical access or badge reader access will only apply to the selected qualification levels. If left empty it will apply to all qualification levels.",
                to="NEMO.qualificationlevel",
                verbose_name="grant access for qualification levels",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_logout_grace_period",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of minutes users have to logout of this tool after their reservation expired before being flagged and abuse email is sent (only applies if reservations are required for this tool).",
                null=True,
                verbose_name="logout grace period",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_reservation_required",
            field=models.BooleanField(
                db_column="reservation_required",
                default=False,
                help_text="Require that users have a current (within 15 minutes) reservation in order to use the tool",
                verbose_name="reservation required",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_shadowing_verification_request_qualification_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Qualification Levels that users can request on this tool through shadowing verification.",
                related_name="shadowing_verification_request_qualification_levels",
                to="NEMO.qualificationlevel",
                verbose_name="shadowing verification request qualification levels",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="_shadowing_verification_reviewers",
            field=models.ManyToManyField(
                blank=True,
                db_table="NEMO_tool_shadowing_verification_reviewers",
                help_text="Users who can approve/deny shadowing verification for this tool. Defaults to facility managers if left blank.",
                related_name="shadowing_verification_reviewer_on_tools",
                to=settings.AUTH_USER_MODEL,
                verbose_name="shadowing verification reviewers",
            ),
        ),
    ]
